"""Initial migration

Revision ID: 39895787520c
Revises: 
Create Date: 2024-09-11 23:02:31.323335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39895787520c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blacklist', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blacklist')

    # ### end Alembic commands ###
